[package]
name = "eyedropper"
version = "0.5.1"
authors = ["FineFindus <finefindusgh@gmail.com>"]
edition = "2021"
description = "A powerful color picker and formatter"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/finefindus/eyedropper"
repository = "https://github.com/finefindus/eyedropper"


#override package level optimization, to always be maximum
[profile.release.package."*"] 
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.17.0"
gtk = {version = "0.5.5", package = "gtk4"}
glib = "0.16.7"
adw = {package = "libadwaita", version = "0.2.1", features = ["v1_2"]}
gtk-macros = "0.3"
ashpd = "0.3.2"
rand = "0.8.5"